-- ===========================================================================
-- BespokeLMS — Seed 002 (mock/demo data). Run AFTER 001_bespokelms_schema.sql.
-- Categories & 28 courses are lifted verbatim from the prototype Course Library
-- so the re-platformed app shows exactly the same catalogue.
-- ===========================================================================
begin;

-- ---- course categories (13) ----
insert into course_categories(name,color_bg,color_text,sort) values('Food Hygiene','bg-sky-50','text-sky-700',0) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Allergen Management','bg-rose-50','text-rose-700',1) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Basic First Aid','bg-red-50','text-red-700',2) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Health & Safety','bg-amber-50','text-amber-700',3) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Safeguarding','bg-violet-50','text-violet-700',4) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Business Essentials','bg-indigo-50','text-indigo-700',5) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Nutrition & Food Quality','bg-emerald-50','text-emerald-700',6) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Dietary Health & Wellbeing','bg-teal-50','text-teal-700',7) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Workplace, Compliance & HR','bg-slate-100','text-slate-600',8) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Premises & Licences','bg-orange-50','text-orange-700',9) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Neurodiversity & Support','bg-fuchsia-50','text-fuchsia-700',10) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Inclusive Service','bg-cyan-50','text-cyan-700',11) on conflict (name) do nothing;
insert into course_categories(name,color_bg,color_text,sort) values('Food Safety Management','bg-lime-50','text-lime-700',12) on conflict (name) do nothing;

-- ---- courses (28) ----
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Food Allergen Awareness for Catering & Hospitality', cc.id, NULL, 90, 499, 1, NULL, 'Identify and manage the 14 major allergens, prevent cross-contamination and meet Food Standards Agency guidance.', 'published' from course_categories cc where cc.name='Allergen Management';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Food Hygiene & Safety Level 2 for Catering & Hospitality', cc.id, 'Level 2', 210, 499, 1, 'RSPH & CIEH mapped', 'CPD-certified food hygiene mapped to RSPH & CIEH Level 2 — HACCP, temperature control and safe food handling.', 'published' from course_categories cc where cc.name='Food Hygiene';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Allergic Reactions & Anaphylaxis in Catering & Hospitality', cc.id, NULL, 30, 399, 1, NULL, 'Recognise and respond quickly to allergic reactions and anaphylaxis in food-service settings.', 'published' from course_categories cc where cc.name='Basic First Aid';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'The Art of Good Customer Service in Catering & Hospitality', cc.id, NULL, 90, 399, 1, NULL, 'Practical skills for delivering warm, professional and memorable customer service every shift.', 'published' from course_categories cc where cc.name='Business Essentials';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Autism Awareness in Catering & Hospitality', cc.id, NULL, 60, NULL, 0, NULL, 'Support autistic colleagues and customers with practical communication and environment tips.', 'coming_soon' from course_categories cc where cc.name='Neurodiversity & Support';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Balanced Nutrition in Education', cc.id, NULL, 60, NULL, 0, NULL, 'How nutrition shapes learning, focus and wellbeing across schools and colleges.', 'coming_soon' from course_categories cc where cc.name='Nutrition & Food Quality';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Bullying & Harassment Awareness', cc.id, NULL, 60, 399, 1, NULL, 'Recognise, prevent and address bullying and harassment in hospitality workplaces.', 'published' from course_categories cc where cc.name='Workplace, Compliance & HR';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Conflict Management in Licensed Venues', cc.id, NULL, 60, 399, 1, NULL, 'Prevent, de-escalate and safely resolve incidents in pubs, bars and licensed venues.', 'published' from course_categories cc where cc.name='Health & Safety';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Cooking Oils & Kitchen Practices', cc.id, NULL, 60, NULL, 0, NULL, 'The science of cooking oils, sustainability and everyday kitchen best practice.', 'coming_soon' from course_categories cc where cc.name='Food Safety Management';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Cost Control & Profitability', cc.id, NULL, 60, NULL, 0, NULL, 'Manage food costs, cut waste and protect margins without compromising quality.', 'coming_soon' from course_categories cc where cc.name='Business Essentials';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Dementia Compassion in Catering & Hospitality', cc.id, NULL, 60, 399, 1, NULL, 'Practical skills and empathy to support customers living with dementia.', 'published' from course_categories cc where cc.name='Safeguarding';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Display Screen Equipment (DSE)', cc.id, NULL, 30, 399, 1, NULL, 'Set up and use display screen equipment safely, with a focus on ergonomics and comfort.', 'published' from course_categories cc where cc.name='Health & Safety';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Fire Safety Awareness Part 1 for Catering & Hospitality', cc.id, NULL, 60, 499, 1, NULL, 'Fire prevention, risk assessment and emergency response for catering environments.', 'published' from course_categories cc where cc.name='Health & Safety';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Food Hygiene & Safety Level 2 for Primary Schools', cc.id, 'Level 2', 120, 399, 1, 'RSPH & CIEH mapped', 'A practical Level 2 course for primary-school catering teams — allergens, HACCP and safe handling.', 'published' from course_categories cc where cc.name='Food Hygiene';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Handling Complaints Effectively in Catering & Hospitality', cc.id, NULL, 30, 399, 1, NULL, 'Turn complaints into loyalty with confident, professional resolution techniques.', 'published' from course_categories cc where cc.name='Business Essentials';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Hydration Matters', cc.id, NULL, 60, NULL, 0, NULL, 'Why hydration matters for staff performance and customer wellbeing.', 'coming_soon' from course_categories cc where cc.name='Dietary Health & Wellbeing';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Inclusive Dining in Catering & Hospitality', cc.id, NULL, 60, NULL, 0, NULL, 'Design menus and service styles that welcome diverse dietary and access needs.', 'coming_soon' from course_categories cc where cc.name='Inclusive Service';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Introduction to Safeguarding in Catering & Hospitality', cc.id, NULL, 60, NULL, 0, NULL, 'Core knowledge and practices to protect and promote the wellbeing of others.', 'coming_soon' from course_categories cc where cc.name='Safeguarding';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Modern Slavery Awareness', cc.id, NULL, 60, 399, 1, NULL, 'Spot the signs of exploitation and know how to report and prevent modern slavery.', 'published' from course_categories cc where cc.name='Safeguarding';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Obstructed Airways & Choking in Catering & Hospitality', cc.id, NULL, 30, 399, 1, NULL, 'First-aid skills to act fast and safely in choking emergencies.', 'published' from course_categories cc where cc.name='Basic First Aid';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Planning First Aid Requirements for Employers & Managers', cc.id, NULL, 60, 399, 1, NULL, 'Assess and plan the right first-aid provision for your workplace.', 'published' from course_categories cc where cc.name='Basic First Aid';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Reducing Food Waste for Operational Excellence', cc.id, NULL, 90, 399, 1, NULL, 'Cut food waste, improve kitchen efficiency and meet UK requirements.', 'published' from course_categories cc where cc.name='Food Hygiene';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Spiking Awareness & Prevention for Bars, Pubs & Nightclubs', cc.id, NULL, 60, 399, 1, NULL, 'Identify, prevent and respond to drink and needle spiking.', 'published' from course_categories cc where cc.name='Safeguarding';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Spillage Management in Licensed Venues', cc.id, NULL, 60, 399, 1, NULL, 'Respond safely to spillages and reduce slip-and-trip risks in licensed venues.', 'published' from course_categories cc where cc.name='Health & Safety';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'The Art of Menu Design in Catering & Hospitality', cc.id, NULL, 60, NULL, 0, NULL, 'Create balanced, appealing menus that meet customer expectations and dietary standards.', 'coming_soon' from course_categories cc where cc.name='Nutrition & Food Quality';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Think Before You Serve: Alcohol Safety Essentials', cc.id, NULL, 60, 399, 1, NULL, 'UK alcohol law, Challenge 25 and refusing service with confidence.', 'published' from course_categories cc where cc.name='Premises & Licences';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Understanding Diabetes in Catering & Hospitality', cc.id, NULL, 60, 399, 1, NULL, 'Support customers with diabetes through informed menu planning and emergency awareness.', 'published' from course_categories cc where cc.name='Dietary Health & Wellbeing';
insert into courses(title,category_id,level,duration_min,price_pennies,credits,accreditation,description,catalog_status) select 'Workplace Wellness for Team Health', cc.id, NULL, 60, NULL, 0, NULL, 'Stress management, nutrition, rest and communication for healthier, happier teams.', 'coming_soon' from course_categories cc where cc.name='Workplace, Compliance & HR';

-- ---- organisations (tenant tree) ----
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('bespokelms','BespokeLMS','platform',NULL,true,'platform',NULL,NULL) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('tp','Turner Price','operator','reseller',true,'operator',NULL,(select id from organizations where slug='bespokelms')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('marchfoods','March Foods','operator','inhouse',false,'operator',NULL,(select id from organizations where slug='bespokelms')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('teachhq','TeachHQ','operator','own_brand',true,'operator',NULL,(select id from organizations where slug='bespokelms')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('foodcompliancehq','FoodComplianceHQ','operator','own_brand',true,'operator',NULL,(select id from organizations where slug='bespokelms')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('all-saints','All Saints'' Catholic Primary School','client',NULL,true,'school','Lanchester',(select id from organizations where slug='tp')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('st-marys','St Mary''s Catholic Primary','client',NULL,true,'school','Durham',(select id from organizations where slug='tp')) on conflict (slug) do nothing;
insert into organizations(slug,name,type,operator_subtype,has_client_layer,subtype,location,parent_id) values('demo-academy','Demo Academy Trust','client',NULL,true,'trust',NULL,(select id from organizations where slug='teachhq')) on conflict (slug) do nothing;

-- ---- teams ----
insert into teams(organization_id,name) select id, 'Kitchen' from organizations where slug='all-saints';
insert into teams(organization_id,name) select id, 'Servery' from organizations where slug='all-saints';
insert into teams(organization_id,name) select id, 'Stores' from organizations where slug='all-saints';
insert into teams(organization_id,name) select id, 'Cleaning' from organizations where slug='all-saints';
insert into teams(organization_id,name) select id, 'Catering Management' from organizations where slug='all-saints';
insert into teams(organization_id,name) select id, 'Kitchen' from organizations where slug='st-marys';
insert into teams(organization_id,name) select id, 'Servery' from organizations where slug='st-marys';
insert into teams(organization_id,name) select id, 'Catering Management' from organizations where slug='st-marys';
insert into teams(organization_id,name) select id, 'Production' from organizations where slug='marchfoods';
insert into teams(organization_id,name) select id, 'Warehouse' from organizations where slug='marchfoods';
insert into teams(organization_id,name) select id, 'Quality & Compliance' from organizations where slug='marchfoods';
insert into teams(organization_id,name) select id, 'Logistics' from organizations where slug='marchfoods';

-- ---- demo accounts (7 tiers/operators) ----
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+BespokeLMS@googlemail.com','Alex Morgan','bespokelms_owner','Platform Owner', org.id, NULL, 'Alex Morgan' from organizations org where org.slug='bespokelms';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+TurnerPrice@googlemail.com','Turner Price Admin','lms_operator_admin','Operator Admin', org.id, NULL, 'Turner Price Admin' from organizations org where org.slug='tp';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+MarchFoods@googlemail.com','March Foods Admin','lms_operator_admin','Operator Admin', org.id, NULL, 'March Foods Admin' from organizations org where org.slug='marchfoods';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+TeachHQ@googlemail.com','TeachHQ Admin','lms_operator_admin','Operator Admin', org.id, NULL, 'TeachHQ Admin' from organizations org where org.slug='teachhq';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+ClientAdmin@googlemail.com','Chris Bennett','client_admin','School Administrator', org.id, NULL, 'Chris Bennett' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+TeamManager@googlemail.com','Sarah Whitfield','team_manager','Catering Supervisor', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Catering Management'), 'Sarah Whitfield' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kemp.house+Learner@googlemail.com','Emma Wilkinson','learner','Catering Manager', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Catering Management'), 'Emma Wilkinson' from organizations org where org.slug='all-saints';

-- ---- Emma Wilkinson learner states (matches the prototype Course Library) ----
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 60, now()-interval '20 days', NULL, NULL, 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Allergic Reactions & Anaphylaxis in Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='The Art of Good Customer Service in Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'assigned', 0, now()-interval '20 days', now() + interval '4 days', NULL, 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Food Hygiene & Safety Level 2 for Primary Schools' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '20 days', NULL, now(), 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Handling Complaints Effectively in Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 30, now()-interval '20 days', NULL, NULL, 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'assigned', 0, now()-interval '20 days', now() + interval '12 days', NULL, 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Planning First Aid Requirements for Employers & Managers' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 45, now()-interval '20 days', NULL, NULL, 'manual' from profiles p, courses co where p.email='kemp.house+Learner@googlemail.com' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;

-- ---- mandatory-course requirements (All Saints) ----
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality';
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Food Allergen Awareness for Catering & Hospitality';
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Fire Safety Awareness Part 1 for Catering & Hospitality';
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Display Screen Equipment (DSE)';
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Modern Slavery Awareness';
insert into course_requirements(scope,scope_ref,course_id,is_mandatory) select 'org',(select id::text from organizations where slug='all-saints'), co.id, true from courses co where co.title='Reducing Food Waste for Operational Excellence';

-- ---- extra learners (All Saints) ----
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'bernadette.kelly@allsaints.demo','Bernadette Kelly','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Kitchen'), 'Bernadette Kelly' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'daniel.owens@allsaints.demo','Daniel Owens','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Kitchen'), 'Daniel Owens' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'priya.patel@allsaints.demo','Priya Patel','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Kitchen'), 'Priya Patel' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'grace.bennett@allsaints.demo','Grace Bennett','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Servery'), 'Grace Bennett' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'aisha.khan@allsaints.demo','Aisha Khan','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Servery'), 'Aisha Khan' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'james.o.connor@allsaints.demo','James O''Connor','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Servery'), 'James O''Connor' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'mark.reilly@allsaints.demo','Mark Reilly','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Stores'), 'Mark Reilly' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'tom.hughes@allsaints.demo','Tom Hughes','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Stores'), 'Tom Hughes' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'liam.foster@allsaints.demo','Liam Foster','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Cleaning'), 'Liam Foster' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'kelly.adams@allsaints.demo','Kelly Adams','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Cleaning'), 'Kelly Adams' from organizations org where org.slug='all-saints';
insert into profiles(email,full_name,role,job_title,organization_id,team_id,avatar_seed) select 'maria.santos@allsaints.demo','Maria Santos','learner','Catering Assistant', org.id, (select t.id from teams t join organizations org on org.id=t.organization_id where org.slug='all-saints' and t.name='Catering Management'), 'Maria Santos' from organizations org where org.slug='all-saints';

-- ---- extra learner enrollments (mandatory set) ----
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='bernadette.kelly@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='daniel.owens@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='priya.patel@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='grace.bennett@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='aisha.khan@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='james.o.connor@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='mark.reilly@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='tom.hughes@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'overdue', 0, now()-interval '30 days', now()-interval '6 days', NULL, 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='liam.foster@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='kelly.adams@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Food Hygiene & Safety Level 2 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Food Allergen Awareness for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'inprogress', 50, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Fire Safety Awareness Part 1 for Catering & Hospitality' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'duesoon', 25, now()-interval '30 days', now()+interval '5 days', NULL, 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Display Screen Equipment (DSE)' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'notstarted', 0, now()-interval '30 days', NULL, NULL, 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Modern Slavery Awareness' on conflict (user_id,course_id) do nothing;
insert into enrollments(user_id,course_id,status,progress_pct,assigned_at,due_at,completed_at,source) select p.id, co.id, 'completed', 100, now()-interval '30 days', NULL, now(), 'auto' from profiles p, courses co where p.email='maria.santos@allsaints.demo' and co.title='Reducing Food Waste for Operational Excellence' on conflict (user_id,course_id) do nothing;

-- ---- AI integration placeholder (admin connects Claude here) ----
insert into ai_integrations(organization_id,provider,display_name,is_enabled,status) values(null,'anthropic','Claude (Anthropic)',false,'unconfigured');

-- ---- per-operator branding settings ----
insert into platform_settings(organization_id,key,value) values (null,'branding','{"product":"BespokeLMS"}'::jsonb) on conflict do nothing;
insert into platform_settings(organization_id,key,value) select id,'branding','{"accent":"#009DE1","name":"Turner Price"}'::jsonb from organizations where slug='tp' on conflict do nothing;
insert into platform_settings(organization_id,key,value) select id,'branding','{"accent":"#2E7D32","name":"March Foods"}'::jsonb from organizations where slug='marchfoods' on conflict do nothing;

-- ---- sample ideas ----
insert into ideas(organization_id,title,description,status,votes) select id,'Dark mode for the dashboard','A full dark theme across all workspaces','planned',42 from organizations where slug='bespokelms';
insert into ideas(organization_id,title,description,status,votes) select id,'HR system integrations','Sync starters and leavers automatically','idea',37 from organizations where slug='bespokelms';
insert into ideas(organization_id,title,description,status,votes) select id,'Bulk certificate export','Download all team certificates as one PDF','idea',18 from organizations where slug='bespokelms';

-- ---- notifications for Emma ----
insert into notifications(user_id,type,title,body) select id,'assignment','New course assigned','Food Hygiene & Safety Level 2 for Primary Schools is due in 4 days' from profiles where email='kemp.house+Learner@googlemail.com';
insert into notifications(user_id,type,title,body) select id,'reminder','Course in progress','Pick up where you left off on Modern Slavery Awareness' from profiles where email='kemp.house+Learner@googlemail.com';
insert into notifications(user_id,type,title,body) select id,'achievement','Certificate earned','You completed Fire Safety Awareness Part 1' from profiles where email='kemp.house+Learner@googlemail.com';

commit;
